package edu.hmc.jane.gui;

import javax.swing.JFrame;
import edu.hmc.jane.Stats;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Histogram.java
 *
 * Created on Jun 25, 2010, 9:08:19 AM
 */

/**
 *
 * @author Tselil
 */
public class HistogramFrame extends JFrame {

    private JPanel histogramDisplay;

    /** Creates new form Histogram */
    public HistogramFrame(Stats.HistoData data, int solnCost) {
        // makes sure the Jane icon is used instead of the default Java icon
        Utils.initIcons(this);
        initComponents();
        setTitle("Random Sample Costs");
        setSize(500, 400);
        histogramDisplay = new Histogram(data, 500, 400);
        setContentPane(histogramDisplay);
        setVisible(true);
    }

    // creates histogram based on a given histogram (cost or p value)
    // uses the width and height of that histogram
    public HistogramFrame(JPanel hist) {
        Utils.initIcons(this);
        initComponents();
        setTitle("Random Sample Costs");
        setSize(hist.getWidth(), hist.getHeight());
        histogramDisplay = hist;
        setContentPane(histogramDisplay);
        setVisible(true);
    }

     private void saveHistogram() {
        Utils.promptAndSave(this, histogramDisplay);
    }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        save_image_menu_option = new javax.swing.JMenuItem();
        close_window_menu_option = new javax.swing.JMenuItem();

        jMenu1.setText("File");

        save_image_menu_option.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S,Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()));
        save_image_menu_option.setText("Save Image");
        save_image_menu_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_image_menu_optionActionPerformed(evt);
            }
        });
        jMenu1.add(save_image_menu_option);

        close_window_menu_option.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_W,Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()));
        close_window_menu_option.setText("Close Window");
        close_window_menu_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_window_menu_optionActionPerformed(evt);
            }
        });
        jMenu1.add(close_window_menu_option);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_image_menu_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_image_menu_optionActionPerformed
        saveHistogram();
    }//GEN-LAST:event_save_image_menu_optionActionPerformed

    private void close_window_menu_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_window_menu_optionActionPerformed
        this.dispose();
    }//GEN-LAST:event_close_window_menu_optionActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem close_window_menu_option;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem save_image_menu_option;
    // End of variables declaration//GEN-END:variables
}
