/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hmc.jane.gui;

import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author andrew
 */
public class ResizeableImageFrame extends javax.swing.JFrame {
    
    private JPanel contents;
    private Dimension originalDimensions;
    private JaneFileChooser parent;

    /**
     * Creates new form ResizeableImageFrame
     */
    public ResizeableImageFrame(JaneFileChooser parent, JPanel image) {
        Utils.initIcons(this);
        initComponents();
        setTitle("Resize Image");
        setSize(image.getWidth(), image.getHeight());
        originalDimensions = new Dimension(image.getWidth(), image.getHeight());
        contents = image;
        this.parent = parent;
        setContentPane(contents);
        setVisible(true);
    }
    
    private void saveImage() {
        parent.changeImageDim(getWidth(), getHeight());
        this.dispose();
    }
    
    private void resetSize() {
        setSize(originalDimensions);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        save_image = new javax.swing.JMenu();
        save_image_menu_item = new javax.swing.JMenuItem();
        reset_size_menu_item = new javax.swing.JMenuItem();
        close_window_menu_item = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        save_image.setText("File");

        save_image_menu_item.setText("Save Image");
        save_image_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_image_menu_itemActionPerformed(evt);
            }
        });
        save_image.add(save_image_menu_item);

        reset_size_menu_item.setText("Reset Size");
        reset_size_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_size_menu_itemActionPerformed(evt);
            }
        });
        save_image.add(reset_size_menu_item);

        close_window_menu_item.setText("Close Window");
        close_window_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_window_menu_itemActionPerformed(evt);
            }
        });
        save_image.add(close_window_menu_item);

        jMenuBar1.add(save_image);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_size_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_size_menu_itemActionPerformed
        resetSize();
    }//GEN-LAST:event_reset_size_menu_itemActionPerformed

    private void save_image_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_image_menu_itemActionPerformed
        saveImage();
    }//GEN-LAST:event_save_image_menu_itemActionPerformed

    private void close_window_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_window_menu_itemActionPerformed
        this.dispose();
    }//GEN-LAST:event_close_window_menu_itemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem close_window_menu_item;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem reset_size_menu_item;
    private javax.swing.JMenu save_image;
    private javax.swing.JMenuItem save_image_menu_item;
    // End of variables declaration//GEN-END:variables
}
