package edu.hmc.jane.gui;

import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SolutionsPerRun.java
 *
 * Created on Jul 22, 2010, 1:05:53 PM
 */

/**
 *
 * @author Tselil
 */
public class SetGeneticParams extends javax.swing.JDialog {

    double selectStr = 0.6;
    double mutRate = 0.8;
    boolean changed = false;

    /** Creates new form SolutionsPerRun */
    public SetGeneticParams(java.awt.Frame owner) {
        super(owner, "Set Genetic Parameters");
        Utils.initIcons(this);
        initComponents();
        getRootPane().setDefaultButton(ok_button);
        select_strength_jFormattedTextField.setValue(selectStr);
        mutation_rate_jFormattedTextField.setValue(mutRate);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ok_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        selection_strength_label = new javax.swing.JLabel();
        mutation_rate_label = new javax.swing.JLabel();
        select_strength_jFormattedTextField = new javax.swing.JFormattedTextField();
        mutation_rate_jFormattedTextField = new javax.swing.JFormattedTextField();

        setTitle("Set Genetic Parameters");
        setLocationByPlatform(true);
        setModal(true);
        setResizable(false);

        ok_button.setText("OK");
        ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        selection_strength_label.setText("Selection Strength");

        mutation_rate_label.setText("Mutation Rate");

        select_strength_jFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.####"))));
        select_strength_jFormattedTextField.setText("0.6");

        mutation_rate_jFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.####"))));
        mutation_rate_jFormattedTextField.setText("0.8");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mutation_rate_label)
                    .add(selection_strength_label))
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(select_strength_jFormattedTextField)
                    .add(mutation_rate_jFormattedTextField)
                    .add(layout.createSequentialGroup()
                        .add(ok_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancel_button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(select_strength_jFormattedTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(selection_strength_label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(mutation_rate_label)
                    .add(mutation_rate_jFormattedTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ok_button, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(cancel_button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        select_strength_jFormattedTextField.setValue(selectStr);
        mutation_rate_jFormattedTextField.setValue(mutRate);
        setVisible(false);
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed
        try {
            double newSel = Double.parseDouble(select_strength_jFormattedTextField.getText());
            double newMut = Double.parseDouble(mutation_rate_jFormattedTextField.getText()); 
            
            if (newSel<0)
                JOptionPane.showMessageDialog(this, "Selection strength may not be negative.");
            else if (newMut<0 || newMut>1)
                JOptionPane.showMessageDialog(this, "Mutation rate must be between 0 and 1, inclusive.");
            else {
                changed = (selectStr != newSel || mutRate != newMut);
                selectStr = newSel;
                mutRate = newMut;
                setVisible(false);
            }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "It appears you didn't enter a number.");
        }

    }//GEN-LAST:event_ok_buttonActionPerformed

    public double getM() {
        return mutRate;
    }
    public double getS() {
        return selectStr;
    }

    public boolean wasChanged() {
        if (changed) {
            changed = false; // Reset for future changes
            return true;
        }
        return false;
    }
    
    public void openWithEditStatus(boolean val) {
        cancel_button.setEnabled(val);
        mutation_rate_jFormattedTextField.setEnabled(val);
        select_strength_jFormattedTextField.setEnabled(val);
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JFormattedTextField mutation_rate_jFormattedTextField;
    private javax.swing.JLabel mutation_rate_label;
    private javax.swing.JButton ok_button;
    private javax.swing.JFormattedTextField select_strength_jFormattedTextField;
    private javax.swing.JLabel selection_strength_label;
    // End of variables declaration//GEN-END:variables
}
