/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hmc.jane.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Rebecca
 */
public class SetSupportParams extends javax.swing.JDialog {

    int popSize = 100;
    
    /**
     * Creates new form SetSupportParams
     */
    public SetSupportParams(java.awt.Frame parent) {
        super(parent, "Set Support Parameters");
        Utils.initIcons(this);
        initComponents();
        getRootPane().setDefaultButton(ok_button);
        pop_size_jFormattedTextField.setValue(popSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancel_button = new javax.swing.JButton();
        ok_button = new javax.swing.JButton();
        pop_size_jFormattedTextField = new javax.swing.JFormattedTextField();
        pop_size_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        ok_button.setText("OK");
        ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buttonActionPerformed(evt);
            }
        });

        pop_size_jFormattedTextField.setText("100");

        pop_size_label.setText("Support Population Size:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(13, 13, 13)
                .add(pop_size_label)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(ok_button)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancel_button))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pop_size_jFormattedTextField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pop_size_jFormattedTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pop_size_label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancel_button)
                    .add(ok_button))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {pop_size_jFormattedTextField, pop_size_label}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getPopSize(){
        return popSize;
    }
    
    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        pop_size_jFormattedTextField.setValue(popSize);
        setVisible(false);
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed
       try {
            int newPopSize = Integer.parseInt(pop_size_jFormattedTextField.getText().replace(",", ""));
            
            if (newPopSize < 100)
                JOptionPane.showMessageDialog(this, "Population size must be at least 100.");
            
            else {
                popSize = newPopSize;
                setVisible(false);
            }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "It appears you didn't enter an integer.");
        }
    }//GEN-LAST:event_ok_buttonActionPerformed

    public void openWithEditStatus(boolean val) {
        cancel_button.setEnabled(val);
        pop_size_jFormattedTextField.setEnabled(val);
        this.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JButton ok_button;
    private javax.swing.JFormattedTextField pop_size_jFormattedTextField;
    private javax.swing.JLabel pop_size_label;
    // End of variables declaration//GEN-END:variables
}
